% Jorge Simón Aznar
% 14/11/2023

close all; 

clear; 

% Load kernels.
METAKR= { 'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls', ... %Leap seconds
    'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0011.tls',...
    'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/lsk/naif0009.tls',...
    'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/lsk/naif0010.tls',...
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp',... %Planetary ephemeris
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc',... %Planet radii and orientation
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/de-403-masses.tpc',... %Masses of planets
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00010.tpc',...
      'https://naif.jpl.nasa.gov/pub/naif/MARS2020/kernels/pck/pck00010.tpc',...
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011_n0066.tpc',...
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/gm_de431.tpc',...
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/gm_de440.tpc',...
      'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/Gravity.tpc',... %Gravity kernel
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_110805_111026_120302.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_111026_120308_120726.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_120308_120825_121109.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_120825_130515_130708.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_130515_131005_131031.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_130515_131005_151210.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_131005_131014_131101.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_131005_131014_131101_reconstruction.bsp.lbl',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_131014_131114_140222.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_131114_140918_141208.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_131114_140918_141208_reconstruction.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_140903_151003_160118.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_151003_160312_160418.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_160312_160522_160614.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_160522_160729_160909.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_160729_160923_161027.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_160729_160924_161026_pj01.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_160923_161115_161121.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_161115_170106_170113.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_170106_170228_170307.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_170228_170422_170427.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_170422_170608_170621.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_170608_170728_170803.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_170728_170918_170922.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_170918_171121_171127.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_171121_180113_180117.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_180113_180307_180312.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_180307_180429_180504.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_180429_180621_180626.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_180620_180812_180821.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_180812_181004_181011.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_181004_181126_181205.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_181126_190118_190124.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_190118_190312_190319.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_190312_190504_190509.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_190504_190626_190627.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_190626_190817_190822.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_190817_191010_191022.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_191010_191201_191210.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_191201_200124_200129.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_200124_200316_200324.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_200316_200508_200512.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_200508_200629_200709.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_200629_200822_200826.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_200822_201014_201016.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_201014_201205_201208.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_201205_210127_210210.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_210127_210321_210329.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_210321_210513_210517.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_210513_210630_210707.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_210630_210813_210825.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_210813_210925_211005.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_210925_211108_211115.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_211108_211222_220104.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_211222_220204_220210.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_220204_220319_220330.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_220319_220502_220510.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_220502_220614_220622.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_220614_220728_220805.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_220728_220909_220913.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_220909_221019_221027.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_221019_221127_221208.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_221127_230104_230111.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230104_230211_230221.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230211_230321_230327.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230321_230428_230504.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230428_230605_230613.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230605_230713_230720.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230713_230820_230823.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/spk_rec_230820_230927_231003.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v12.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de441_part-1.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de441_part-2.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/mars_iau2000_v1.tpc',...
        'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/fk/planets/earth_assoc_itrf93.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/MARS2020/kernels/spk/de430s.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/MARS2020/kernels/spk/de438s.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/MARS2020/kernels/spk/mar097.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/MARS2020/kernels/spk/mar097s.bsp',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v01.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v02.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v07.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v08.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v09.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v10.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v11.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v12.tf',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/pck/pck00008.tpc',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/pck/pck00009.tpc',...
        'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/pck/pck00010.tpc',...
        'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/jup344.cmt', ... %Jupiter moons kernel
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/jup346.cmt', ... %Jupiter kernel
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls', ... %Leap seconds
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp',... %Planetary ephemeris
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc',... %Planet radii and orientation
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/de-403-masses.tpc',... %Masses of planets
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/moon_pa_de403_1950-2198.bpc',... %Masses of moons
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/Gravity.tpc',... %Gravity kernel
          'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/jup365.bsp',...
          'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/fk/juno_v12.tf',...
          'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/ck/juno_sa_nom_110801_171101_v01.bc',...
          'https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/sclk/JNO_SCLKSCET.00158.tsc'};
initSPICEv(fullK(METAKR));

MAXWIN  =  10000;
TIMFMT  = 'YYYY-MON-DD HR:MN:SC.###### (TDB) ::TDB ::RND';
OCCTYP  = 'ANY';


% Store the time bounds of our search interval in
% the cnfine confinement window.

et = cspice_str2et( { '2011 AUG 05 17:34:00 TDB',                ...
                      '2018 FEB 20 23:59:00 TDB'} );
cnfine = cspice_wninsd( et(1), et(2) );

% Select a 2-minute step. We'll ignore any occultations
% lasting less than 2 minutes.

step    = 120.;

% The observation location is the Sun.

obsrvr  = 'sun';
shape   = 'POINT';
M_Shape = 'ELLIPSOID';
abcorr = 'lt';
Juno_data = cell(1, 10);
   
   % Do a search for occultations of Juno by
   % any body.
   
   for j=7:10
   %j = 3;  
      if isequal(j,1)
         front  = 'MERCURY';
         fframe = 'IAU_MERCURY';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Mercury';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,2)
         front  = 'VENUS';
         fframe = 'IAU_VENUS';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Venus';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,3)
         front  = 'EARTH';
         fframe = 'IAU_EARTH';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Earth';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,4)
         front  = 'MOON';
         fframe = 'IAU_MOON';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Moon';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,5)
         front  = 'MARS';
         fframe = 'IAU_MARS';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Mars';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,6)
         front  = 'JUPITER';
         fframe = 'IAU_JUPITER';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Jupiter';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,7)
         front  = 'IO';
         fframe = 'IAU_IO';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Io';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,8)
         front  = 'EUROPA';
         fframe = 'IAU_EUROPA';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Europa';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,9)
         front  = 'CALLISTO';
         fframe = 'IAU_CALLISTO';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Callisto';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
      if isequal(j,10)
         front  = 'GANYMEDE';
         fframe = 'IAU_GANYMEDE';
         back   = 'JUNO';
         bframe = 'NONE';
         Juno_data{j} = cspice_gfoclt( OCCTYP, front, M_Shape, fframe,  ...
                              back, shape, bframe, abcorr,  ...
                              obsrvr, step, cnfine, MAXWIN );
         name = 'Occultation by Ganymede';
         printTimeWindow(Juno_data{j}, front, name, TIMFMT);
      end
   end
toc                                      % For computation time

% It's always good form to unload kernels after use,
% particularly in Matlab due to data persistence.

cspice_kclear